const test = require('node:test'); const assert = require('node:assert/strict');
const { loadConfig } = require('../../src/config'); const { ConfigurationError } = require('../../src/utils/errors');
const { TaskState } = require('../../src/core/taskState'); const { AgentRegistry } = require('../../src/core/agentRegistry'); const { ToolRegistry } = require('../../src/core/toolRegistry'); const { LLMClient } = require('../../src/llm/client'); const { Orchestrator } = require('../../src/core/orchestrator'); const { MockProvider } = require('../../src/llm/mockProvider'); const { normalizeResponse } = require('../../src/llm/client'); const { validateArguments } = require('../../src/core/schemaValidation');
const { formatCliError } = require('../../src/index');
const { loadProvider } = require('../../src/llm/provider');
test('configuration defaults and environment values', () => { const c=loadConfig({MODEL_NAME:'test', WORKSPACE_ROOT:process.cwd()}); assert.equal(c.apiKey,''); assert.equal(c.model,'test'); assert.equal(c.retryLimit,2); });
test('concurrency and step timeout configuration are bounded', () => { assert.equal(loadConfig({}).maxConcurrency,2); for(const value of ['0','9','2.5','NaN','999999999'])assert.throws(()=>loadConfig({MAX_CONCURRENCY:value}),ConfigurationError); for(const value of ['0','-1','NaN','999999999'])assert.throws(()=>loadConfig({STEP_TIMEOUT_MS:value}),ConfigurationError); assert.equal(loadConfig({MAX_CONCURRENCY:'1'}).maxConcurrency,1); assert.equal(loadConfig({MAX_CONCURRENCY:'8'}).maxConcurrency,8); assert.throws(()=>loadConfig({MAX_PLAN_STEPS:'101'}),ConfigurationError); assert.throws(()=>loadConfig({WORKSPACE_ROOT:'/path/that/does/not/exist'}),ConfigurationError); });
test('missing API key is rejected only when model is called without exposing credential values', async () => { const client=new LLMClient({provider:{generate:async()=>1},config:loadConfig({})}); await assert.rejects(client.generate('x'), ConfigurationError); const message=formatCliError(new Error('provider rejected secret-value'), 'secret-value'); assert.ok(!message.includes('secret-value')); assert.match(message,/REDACTED/); });
test('TaskState is structured and serializable', () => { const s=new TaskState('fix it','id'); s.record('created'); assert.equal(s.toJSON().id,'id'); assert.equal(s.toJSON().executionHistory.length,1); });
test('workflow outcome distinguishes partial failure, timeout, blocked, and configuration errors', () => { const s=new TaskState('issue'); assert.equal(s.toJSON().outcome,'in_progress'); s.schedulerResult={successfulSteps:['a'],failedSteps:['b'],blockedSteps:[{stepId:'c'}],timedOutSteps:[]}; assert.equal(s.toJSON().outcome,'partial_failure'); s.schedulerResult={successfulSteps:[],failedSteps:['a'],blockedSteps:[],timedOutSteps:['a']}; assert.equal(s.toJSON().outcome,'timeout'); s.schedulerResult={successfulSteps:[],failedSteps:['a'],blockedSteps:[{stepId:'b'}],timedOutSteps:[]}; assert.equal(s.toJSON().outcome,'blocked'); s.planningError={code:'ConfigurationError'}; assert.equal(s.toJSON().outcome,'configuration_error'); });
test('missing and malformed provider configuration fails with a clear configuration error', () => { assert.throws(()=>loadProvider(''),error=>error.name==='ConfigurationError'&&/LLM_PROVIDER_MODULE/.test(error.message)); assert.throws(()=>loadProvider('./missing-provider-module.js'),error=>error.name==='ConfigurationError'&&/could not be loaded/.test(error.message)); });
test('malformed planner output is a structured planning failure', async () => { const registry=new AgentRegistry(); const result=await new Orchestrator({llm:new LLMClient({provider:new MockProvider([{type:'final',content:'not JSON'}]),config:loadConfig({})}),toolRegistry:new ToolRegistry(),agentRegistry:registry}).run('Investigate issue'); assert.equal(result.status,'planning_failed'); assert.equal(result.outcome,'failure'); assert.match(result.planningError.message,/not valid JSON/); assert.deepEqual(result.agentResults,[]); });
test('missing AI_API_KEY becomes a structured configuration outcome before provider use', async () => { let called=false;const result=await new Orchestrator({llm:new LLMClient({provider:{generate:async()=>{called=true;}},config:loadConfig({})}),toolRegistry:new ToolRegistry(),agentRegistry:new AgentRegistry()}).run('Investigate issue');assert.equal(called,false);assert.equal(result.status,'planning_failed');assert.equal(result.outcome,'configuration_error');assert.match(result.planningError.message,/AI_API_KEY is required/); });
test('partial failure result identifies completed, failed, and blocked steps', async () => { const agents=new AgentRegistry();const mk=(name,execute)=>({name,description:name,capabilities:[],tools:[],execute});agents.register(mk('broken',async()=>{throw new Error('fixture failure')}));agents.register(mk('dependent',async()=>({agent:'dependent',status:'completed',summary:'should not run'})));agents.register(mk('healthy',async()=>({agent:'healthy',status:'completed',summary:'independent work completed'})));const plan={goal:'isolate independent branch failure',steps:[{id:'broken-step',agent:'broken',task:'fail intentionally',dependsOn:[]},{id:'dependent-step',agent:'dependent',task:'must be blocked',dependsOn:['broken-step']},{id:'healthy-step',agent:'healthy',task:'continue',dependsOn:[]}]};const result=await new Orchestrator({llm:new LLMClient({provider:new MockProvider([{type:'final',content:JSON.stringify(plan)}]),config:loadConfig({})}),toolRegistry:new ToolRegistry(),agentRegistry:agents,config:{maxConcurrency:2,maxAgentRetries:0}}).run('Exercise partial failure');assert.equal(result.outcome,'partial_failure');assert.deepEqual(result.summary.completedSteps,['healthy-step']);assert.deepEqual(result.summary.failedSteps,['broken-step']);assert.deepEqual(result.summary.blockedSteps,[{id:'dependent-step',blockedBy:['broken-step']}]);assert.deepEqual(result.summary.selectedAgents,['broken','healthy','dependent']); });
test('model errors containing the configured credential are redacted', async () => { const secret=['sensitive','test','value'].join('-'); const client=new LLMClient({provider:{generate:async()=>{throw new Error(`Rejected ${secret}`)}},config:{apiKey:secret,model:'unspecified',temperature:0,maxTokens:20}}); await assert.rejects(client.generate({messages:[{role:'user',content:'hello'}]}),error=>!error.message.includes(secret)&&error.message.includes('[REDACTED]')); });
test('final verification obtains a fresh post-workflow Git diff and requires review evidence', async () => { const calls=[]; const tools={get:name=>({execute:async()=>{calls.push(name);return name==='git_diff'?'fresh diff':'## main\n';}})}; const orchestrator=new Orchestrator({toolRegistry:tools}); const state=new TaskState('fix issue'); state.filesChanged=['src/fix.js']; state.actualChanges=[{path:'src/fix.js',succeeded:true,afterExists:true,afterHash:'sha256'}]; state.testRuns=[{success:true,exitCode:0,command:['npm','test']}]; state.testResults=[{passed:true}]; state.reviewResults=[{agent:'reviewer',reviewOutcome:'reviewed',reviewEvidence:{diffInspected:true,statusInspected:true},artifacts:[{tool:'git_diff',success:true},{tool:'git_status',success:true}]}]; state.executionHistory.push({event:'tool_result',details:{tool:'git_diff',success:true,data:'stale pre-change diff'}}); assert.equal(await orchestrator.finalVerify([],state),true); assert.deepEqual(calls,['git_diff','git_status']); assert.equal(state.executionHistory.at(-1).details.bytes,10); state.reviewResults=[]; assert.equal(await orchestrator.finalVerify([],state),false); });
test('registries validate and expose members', () => { const a=new AgentRegistry(); const agent={name:'x',capabilities:[],tools:[],execute(){}}; a.register(agent); assert.equal(a.get('x'),agent); assert.equal(a.has('x'),true); assert.throws(()=>a.register(agent)); const t=new ToolRegistry(); const tool={name:'t',description:'test',inputSchema:{},permissions:[],execute(){}}; t.register(tool); assert.equal(t.list()[0].name,'t'); });


test('LLM responses normalize and malformed results are rejected', () => { assert.deepEqual(normalizeResponse({type:'final',content:'done'}),{type:'final',content:'done'}); assert.throws(()=>normalizeResponse({wat:1})); });
test('tool schema validation rejects missing, wrong-type and extra arguments', () => { const schema={type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false}; assert.throws(()=>validateArguments(schema,{})); assert.throws(()=>validateArguments(schema,{query:3})); assert.throws(()=>validateArguments(schema,{query:'x',extra:1})); });
test('tool schemas are exposed without executable implementation', () => { const registry=new ToolRegistry(); registry.register({name:'x',description:'read',inputSchema:{type:'object'},permissions:['filesystem:read'],execute(){}}); assert.deepEqual(registry.list(),[{name:'x',description:'read',inputSchema:{type:'object'},permissions:['filesystem:read']}]); });
