const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const {execFile}=require('node:child_process');const {promisify}=require('node:util');
const {APISpecialistAgent,API_TOOLS}=require('../../src/agents/apiSpecialist');const {createCoreAgents}=require('../../src/agents/llmAgents');const {AgentRegistry}=require('../../src/core/agentRegistry');const {ToolRegistry}=require('../../src/core/toolRegistry');const {Orchestrator}=require('../../src/core/orchestrator');const {LLMClient}=require('../../src/llm/client');const {MockProvider}=require('../../src/llm/mockProvider');const {createFileTools}=require('../../src/tools/fileTools');const {createSearchTool}=require('../../src/tools/searchTools');const {createGitTools}=require('../../src/tools/gitTools');const {createEditTools}=require('../../src/tools/editTools');const {createRunTestsTool}=require('../../src/tools/testTools');const {createCommandTool}=require('../../src/tools/commandTools');const {validatePlan}=require('../../src/core/taskPlanner');const {ContextManager}=require('../../src/core/contextManager');
const execFileAsync=promisify(execFile);async function temporary(fn){const root=await fs.mkdtemp(path.join(os.tmpdir(),'harness-p5-'));try{return await fn(root)}finally{await fs.rm(root,{recursive:true,force:true})}}async function gitInit(root){await execFileAsync('git',['init','-q'],{cwd:root});await execFileAsync('git',['add','.'],{cwd:root});await execFileAsync('git',['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','fixture baseline'],{cwd:root});}
const configFor=root=>({workspaceRoot:root,model:'mock',temperature:0,maxTokens:1000,maxAgentSteps:12,maxToolCalls:24,maxExecutionTimeMs:30000,toolTimeoutMs:5000,maxFixAttempts:3,maxAgentRetries:0,maxPlanSteps:12,allowedPermissions:['filesystem:read','filesystem:write','git:read','process:test'],commandTimeoutMs:10000,maxCommandOutputBytes:100000});
function toolsFor(config){const registry=new ToolRegistry();[...createFileTools(config),createSearchTool(config),...createGitTools(config),...createEditTools(config),createRunTestsTool({workspaceRoot:config.workspaceRoot,testCommand:config.testCommand,timeoutMs:10000}),createCommandTool({workspaceRoot:config.workspaceRoot,allowedCommands:['node --version']})].forEach(tool=>registry.register(tool));return registry;}
function agentsFor(){const registry=new AgentRegistry();createCoreAgents().forEach(agent=>registry.register(agent));return registry;}
const API_PLAN={goal:'Fix missing email API response',steps:[{id:'research',agent:'researcher',task:'Locate user endpoint and tests',dependsOn:[]},{id:'api-investigation',agent:'api_specialist',task:'Analyze missing email handling',dependsOn:['research']},{id:'implement',agent:'developer',task:'Return the expected validation response',dependsOn:['api-investigation']},{id:'verify',agent:'qa',task:'Run API tests',dependsOn:['implement']},{id:'review',agent:'reviewer',task:'Review the API change',dependsOn:['verify']}]};
function apiWorkflowResponses(){return[
 {type:'final',content:JSON.stringify(API_PLAN)},
 {type:'final',content:JSON.stringify({summary:'Located user request handler and API tests.',findings:['createUser handles POST body'],relevantFiles:['src/routes/users.js','test/users.test.js']})},
 {type:'tool_call',tool:'search_code',arguments:{query:'createUser'}},{type:'tool_call',tool:'read_file',arguments:{path:'src/routes/users.js'}},{type:'tool_call',tool:'read_file',arguments:{path:'test/users.test.js'}},
 {type:'final',content:JSON.stringify({status:'success',summary:'Missing email falls into the generic error handler.',findings:[{file:'src/routes/users.js',line:3,evidence:'body.email.toLowerCase() runs inside try without validating email.',issue:'A missing email throws and is converted to HTTP 500.'}],rootCause:'No required-email validation occurs before lowercasing.',recommendations:['Return a 400 validation response before accessing email.toLowerCase().'],relatedTests:['test/users.test.js']})},
 {type:'tool_call',tool:'edit_file',arguments:{path:'src/routes/users.js',oldText:'const email = body.email.toLowerCase();',newText:'const email = String(body.email).toLowerCase();'}},{type:'final',content:JSON.stringify({summary:'Applied a first correction.',filesChanged:['src/routes/users.js'],changes:['Avoided the thrown property access']})},
 {type:'tool_call',tool:'run_tests',arguments:{}},{type:'final',content:JSON.stringify({summary:'The missing-email test still fails.',tests:[]})},
 {type:'tool_call',tool:'edit_file',arguments:{path:'src/routes/users.js',oldText:'    const email = String(body.email).toLowerCase();',newText:"    if (typeof body?.email !== 'string' || !body.email.trim()) return { status: 400, body: { error: 'email is required' } };\n    const email = body.email.toLowerCase();"}},{type:'final',content:JSON.stringify({summary:'Added explicit required-email validation.',filesChanged:['src/routes/users.js'],changes:['Return a 400 response for missing email']})},
 {type:'tool_call',tool:'run_tests',arguments:{}},{type:'final',content:JSON.stringify({summary:'API tests pass.',tests:[]})},
 {type:'tool_call',tool:'git_status',arguments:{}},{type:'tool_call',tool:'git_diff',arguments:{}},{type:'final',content:JSON.stringify({summary:'The diff implements the API specialist recommendation.',findings:[],filesChanged:['src/routes/users.js'],unresolvedIssues:[]})}
];}

test('API Specialist registration, capabilities, and strictly read-only tool scope',()=>{const registry=agentsFor();const api=registry.get('api_specialist');assert.ok(api instanceof APISpecialistAgent);assert.deepEqual(api.capabilities,['api-debugging','api-testing','http-analysis','request-response-analysis']);assert.deepEqual(api.tools,API_TOOLS);assert.equal(api.tools.includes('edit_file'),false);assert.equal(api.tools.includes('run_command'),false);for(const name of API_TOOLS)assert.ok(api.tools.includes(name));});
test('API Specialist rejects malformed structured findings and uncertain results',async()=>{const api=new APISpecialistAgent();await assert.rejects(api.execute({}, {runToolLoop:async()=>({content:'not json',toolResults:[]})}),/malformed JSON/);await assert.rejects(api.execute({}, {runToolLoop:async()=>({content:JSON.stringify({status:'success',summary:'bad line',findings:[{file:'x.js',line:0,evidence:'x',issue:'y'}],rootCause:'x',recommendations:['fix'],relatedTests:[]}),toolResults:[]})}),/positive line/);const uncertain=await api.execute({}, {runToolLoop:async()=>({content:JSON.stringify({status:'uncertain',summary:'Need more evidence',findings:[],rootCause:'',recommendations:[],relatedTests:[]}),toolResults:[]})});assert.equal(uncertain.status,'failed');assert.equal(uncertain.investigationStatus,'uncertain');});
test('API Specialist cannot write files or invoke unregistered arbitrary commands',async()=>temporary(async root=>{const file=path.join(root,'source.js');await fs.writeFile(file,'original');const config=configFor(root);const registry=toolsFor(config);const provider=new MockProvider([{type:'tool_call',tool:'read_file',arguments:{path:'../../etc/passwd'}},{type:'tool_call',tool:'edit_file',arguments:{path:'source.js',oldText:'original',newText:'changed'}},{type:'tool_call',tool:'run_command',arguments:{command:'node',args:['-e','process.exit(0)']}},{type:'tool_call',tool:'read_file',arguments:{path:'source.js'}},{type:'final',content:JSON.stringify({status:'success',summary:'Read-only investigation.',findings:[{file:'source.js',line:1,evidence:'original',issue:'evidence'}],rootCause:'The observed issue is in source.js.',recommendations:['Review source.'],relatedTests:[]})}]);const llm=new LLMClient({provider,config});const tools=toolsFor(config);const loop=require('../../src/core/toolLoop').ToolLoop;const {TaskState}=require('../../src/core/taskState');const state=new TaskState('api');const runtime=new loop({llm,toolRegistry:tools,config:{...config,allowedPermissions:config.allowedPermissions},state,startedAt:Date.now()});const result=await new APISpecialistAgent().execute({issue:'inspect'}, {runToolLoop:opts=>runtime.run(opts)});assert.equal(result.status,'completed');assert.equal(await fs.readFile(file,'utf8'),'original');assert.deepEqual(state.executionHistory.filter(entry=>entry.event==='tool_result'&&!entry.details.success).map(entry=>entry.details.error.code),['PermissionError','PERMISSION_DENIED','PERMISSION_DENIED']);}));
test('API routing is dynamic and an implementation intent cannot pass with a research-only plan',async()=>{const agents=agentsFor();const plan={goal:'Update docs',steps:[{id:'research',agent:'researcher',task:'Inspect README',dependsOn:[]}]};const provider=new MockProvider([{type:'final',content:JSON.stringify(plan)},{type:'final',content:JSON.stringify({summary:'README location found.',findings:[],relevantFiles:['README.md']})}]);const config=configFor(process.cwd());const result=await new Orchestrator({llm:new LLMClient({provider,config}),toolRegistry:toolsFor(config),agentRegistry:agents,config}).run('Update the README installation instructions.');assert.equal(result.outcome,'verification_failed');assert.equal(result.verification.details.type,'no_code_change');assert.equal(result.completedAgents.includes('api_specialist'),false);assert.equal(result.plan.some(step=>step.agent==='api_specialist'),false);});
test('API plan cannot request unauthorized tools and missing registration fails structurally',async()=>{const agents=agentsFor();const toolRegistry=toolsFor(configFor(process.cwd()));const bad={goal:'api',steps:[{id:'api',agent:'api_specialist',task:'inspect',dependsOn:[],tools:['edit_file']}]};assert.throws(()=>validatePlan(bad,agents.list(),toolRegistry,{allowedPermissions:configFor(process.cwd()).allowedPermissions}),/tools unavailable/);const missing=new AgentRegistry();const {TaskPlanner}=require('../../src/core/taskPlanner');const llm=new LLMClient({provider:new MockProvider([{type:'final',content:JSON.stringify({goal:'api',steps:[{id:'api',agent:'api_specialist',task:'inspect',dependsOn:[]}]})}]),config:configFor(process.cwd())});const result=await new Orchestrator({llm,toolRegistry,agentRegistry:missing}).run('API issue');assert.equal(result.status,'planning_failed');assert.match(result.planningError.message,/unavailable agent/);});
test('invalid API capability declarations are rejected by existing registry',()=>{const registry=new AgentRegistry();const api=new APISpecialistAgent();const invalid=Object.create(Object.getPrototypeOf(api));Object.assign(invalid,api);invalid.capabilities='api-debugging';assert.throws(()=>registry.register(invalid),/capabilities must be a string array/);});
test('API timeout becomes a structured orchestrator failure',async()=>{const plan={goal:'investigate API',steps:[{id:'api',agent:'api_specialist',task:'inspect API',dependsOn:[]}]};const provider=new MockProvider([{type:'final',content:JSON.stringify(plan)},()=>new Promise(()=>{})]);const config={...configFor(process.cwd()),maxExecutionTimeMs:40,maxAgentRetries:0};const result=await new Orchestrator({llm:new LLMClient({provider,config}),toolRegistry:toolsFor(config),agentRegistry:agentsFor(),config}).run('Investigate API request');assert.equal(result.status,'failed');assert.equal(result.failedAgents.includes('api_specialist'),true);assert.match(result.errors[0].message,/timed out/);});
test('API findings propagate through dependencies into Developer context',()=>{const manager=new ContextManager();const apiStep={id:'api',agent:'api_specialist',task:'investigate',dependsOn:['research']};const developer={id:'dev',agent:'developer',task:'fix',dependsOn:['api']};const apiResult={agent:'api_specialist',summary:'Missing email causes 500',findings:[{file:'src/routes/users.js',line:3,evidence:'body.email access',issue:'throws'}],rootCause:'Validation missing',recommendations:['Return 400'],relatedTests:['test/users.test.js']};const state={findings:[],relevantFiles:[],testResults:[],actualChanges:[]};const context=manager.build({issue:'fix API',step:developer,dependencyResults:[{step:apiStep,result:apiResult}],state});assert.equal(context.apiInvestigations[0].rootCause,'Validation missing');assert.equal(context.apiInvestigations[0].findings[0].evidence,'body.email access');assert.ok(context.relevantFiles.includes('test/users.test.js'));});
test('API specialist drives developer change, QA recovery, review, and final verification',async()=>temporary(async tempRoot=>{const root=path.join(tempRoot,'api-bug');await fs.cp(path.resolve(__dirname,'../fixtures/api-bug'),root,{recursive:true});await gitInit(root);const config=configFor(root);const provider=new MockProvider(apiWorkflowResponses());const result=await new Orchestrator({llm:new LLMClient({provider,config}),toolRegistry:toolsFor(config),agentRegistry:agentsFor(),config}).run('POST /users returns 500 when email is missing.');assert.equal(result.status,'verified');assert.equal(result.outcome,'success');assert.equal(result.summary.status,'verified');assert.ok(result.summary.selectedAgents.includes('api_specialist'));assert.ok(result.summary.completedSteps.includes('verify'));assert.deepEqual(result.summary.changedFiles,['src/routes/users.js']);assert.equal(result.summary.testResults.at(-1).passed,true);assert.equal(result.summary.recoveryAttempts,1);assert.equal(result.summary.reviewResult.agent,'reviewer');assert.equal(result.summary.verification.status,'passed');assert.equal(result.recoveryAttempts,1);assert.equal(result.testRuns.length,2);assert.deepEqual(result.testRuns.map(run=>run.success),[false,true]);assert.equal(result.completedAgents.filter(agent=>agent==='api_specialist').length,1);assert.equal(result.reviewResults.length,1);assert.ok(result.agentResults.find(agent=>agent.agent==='api_specialist').findings[0].evidence.includes('body.email.toLowerCase()'));const developerRequest=provider.requests.find(request=>request.messages[0]?.content.includes('Implement the recommended fix'));assert.ok(developerRequest);const developerContext=JSON.parse(developerRequest.messages[1].content);assert.equal(developerContext.apiInvestigations[0].rootCause,'No required-email validation occurs before lowercasing.');assert.equal(developerContext.apiInvestigations[0].relatedTests[0],'test/users.test.js');assert.ok(developerContext.apiInvestigations[0].findings[0].evidence.includes('body.email.toLowerCase()'));assert.equal((await fs.readFile(path.join(root,'src/routes/users.js'),'utf8')).includes("return { status: 400"),true);assert.equal(result.testRuns[0].exitCode,1);assert.equal(result.testRuns[1].exitCode,0);}));

test('malformed API output fails structurally without storing corrupt results',async()=>{const plan={goal:'inspect api',steps:[{id:'api',agent:'api_specialist',task:'investigate',dependsOn:[]}]};const config={...configFor(process.cwd()),maxAgentRetries:0};const provider=new MockProvider([{type:'final',content:JSON.stringify(plan)},{type:'final',content:'not JSON'}]);const state=await new Orchestrator({llm:new LLMClient({provider,config}),toolRegistry:toolsFor(config),agentRegistry:agentsFor(),config}).run('API fails');assert.equal(state.status,'failed');assert.deepEqual(state.agentResults,[]);assert.deepEqual(state.failedAgents,['api_specialist']);assert.equal(state.activeAgents.length,0);});
